"""A/B: my per-step base driving vs upstream's own full-scan sampler.

Motivated by an anomaly in run 698463: latents generated by the base sampler have std ~0.39, where
SD-VAE latents scaled by 0.18215 should have std ~1, and the decoded images are washed out. Worse,
the deficit GROWS with the number of transitions (std 0.53 at N=4, 0.39 at N=6), which is what a
transition that leaks variance every step would look like.

Two possible causes, and this script separates them:

  A. my driving is wrong  -- calling `run_sampler_step` per step differs somehow from upstream's
     `jax.lax.scan` over the same steps (key threading, the x_final composition, ...).
  B. it is inherent      -- upstream's own sampler at these settings does the same thing, and the
     cause is elsewhere (cfg_scale=1.0, too few steps, the model itself).

Same config, same seed, same step count; the ONLY difference is who drives the loop. If both give
~0.39 the answer is B and my bridge is exonerated.
"""

from __future__ import annotations

import os
import sys

import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths  # noqa: E402

N_STEPS = 6
INNER = 8
BATCH = 16
LABEL = 207
SEED = 0


def main() -> int:
    info = paths.preflight()
    from creativity_measure.backends.diamond_maps_jax import DiamondMapsBackend

    for cfg_scale in (1.0, 4.0):
        print(f"\n{'=' * 78}\ncfg_scale = {cfg_scale}\n{'=' * 78}", flush=True)
        backend = DiamondMapsBackend(
            label=LABEL, cfg_scale=cfg_scale,
            base_ckpt=info["base_ckpt"], posterior_ckpt=info["posterior_ckpt"],
            repo_root=info["diamond_maps_root"],
            n_steps=N_STEPS, base_inner_steps=INNER, seed=SEED,
        )
        jnp = backend._jnp
        sampling = backend._sampling

        # ---- A: my per-step driving -----------------------------------------------------------
        backend.reset_rng(SEED)
        x = backend.init_particles(BATCH)
        x0 = x.clone()
        for step in range(N_STEPS):
            x = backend.base_step(x, step)
        print(f"  mine (per-step run_sampler_step): std={float(x.std()):.4f} "
              f"mean={float(x.mean()):+.4f} absmax={float(x.abs().max()):.2f}", flush=True)

        # ---- B: upstream's own full-scan sampler, same x0 and same keys ------------------------
        sampler = sampling.create_batched_sampler(backend._base_spec)
        backend.reset_rng(SEED)
        _ = backend.init_particles(BATCH)          # advance the torch gen identically
        keys = backend._next_keys("base", BATCH)   # the same first key block mine consumed
        out, _, _, _, _ = sampler(
            backend._base_vars,
            False,
            backend._to_jax(x0),
            keys,
            backend._labels(BATCH),
        )
        xb = backend._to_torch(out)
        print(f"  upstream (run_batched_sampler):   std={float(xb.std()):.4f} "
              f"mean={float(xb.mean()):+.4f} absmax={float(xb.abs().max()):.2f}", flush=True)
        print(f"  max |mine - upstream| = {float((x - xb).abs().max()):.4e}", flush=True)

        # ---- per-step variance trace: where does it leak? --------------------------------------
        backend.reset_rng(SEED)
        xt = backend.init_particles(BATCH)
        trace = [float(xt.std())]
        for step in range(N_STEPS):
            xt = backend.base_step(xt, step)
            trace.append(float(xt.std()))
        print(f"  std after each transition: {[round(v, 3) for v in trace]}", flush=True)

        img = backend.decode(x.reshape(BATCH, -1)).cpu()
        print(f"  decoded: range [{float(img.min()):.2f}, {float(img.max()):.2f}] "
              f"std={float(img.std()):.3f}", flush=True)
        np.save(f"ab_images_cfg{cfg_scale}.npy", img.numpy())

    print("\nIf the two rows agree, the bridge is exonerated and the cause is the config "
          "(cfg_scale / step count / model), not the driving.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
