[project]
name = "creativity-measure"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "torch",
  "jaxtyping",
  "matplotlib",
  "numpy<2",
  "scikit-learn",
]

[project.optional-dependencies]
dev = [
  "pyright",
  "beartype",
  "pytest",
  "nbdime",
]

[tool.pyright]
include = ["creativity_measure", "tests"]
pythonVersion = "3.11"
typeCheckingMode = "basic"
reportPrivateImportUsage = false
